# using default_language_version
default_language_version:
  node: 16.14.2

repos:
  # -------------------------- Version control checks -------------------------- #
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-merge-conflict
        name: Check for merge conflicts
      - id: check-vcs-permalinks
        name: Ensure links to VCS websites are permalinks
      - id: detect-private-key
        name: Detect private key
      - id: check-case-conflict
        name: Check issues with file name casing
      - id: check-symlinks
        name: Check for symlinks which point to nothing
      - id: destroyed-symlinks
        name: Check for destroyed symlinks

  - repo: https://github.com/sirosen/check-jsonschema
    rev: 0.18.3
    hooks:
      - id: check-github-workflows
        name: Validate GitHub workflows
        types: [yaml]

  # ----------------------------- Check file issues ---------------------------- #
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-toml
        name: Check TOML
        types: [toml]
      - id: check-yaml
        name: Check YAML
        args: [--allow-multiple-documents]
        types: [yaml]
      - id: end-of-file-fixer
        name: Fix end of files
        types: [text]
      - id: trailing-whitespace
        name: Trim trailing whitespace
        args: [--markdown-linebreak-ext=md]
        types: [text]
      - id: mixed-line-ending
        name: Check line endings
      - id: fix-encoding-pragma
        name: Remove any encoding pragma
        args: [--remove]

  # ----------------------------- Automatic linters ---------------------------- #
  - repo: https://github.com/sirosen/texthooks
    rev: 0.4.0
    hooks:
      - id: fix-smartquotes
        name: Fix Smart Quotes

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.253
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]

    # -------------------------------- Formatting -------------------------------- #
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0-alpha.1
    hooks:
      - id: prettier
        name: Prettier
        exclude: ^.*/?CHANGELOG\.md$
  - repo: https://github.com/myint/docformatter
    rev: v1.5.0
    hooks:
      - id: docformatter
        name: Format docstrings
        types: [python]
        args: [--in-place, --wrap-summaries=99, --wrap-descriptions=99]
  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black-jupyter
        types: [python]
        name: Format code
